openapi: 3.0.0
info:
  title: H Plus Sports API
  version: 1.0.0
tags:
  - name: Product
paths:
  /product/{productId}:
    get:
      tags:
        - Product
      parameters:
        - in: path
          name: productId
          description: Product id
          required: true
          schema:
            type: integer
            example: 123
        - in: header
          name: customer-security-header
          description: Customer token
          required: false
          schema:
            type: string
      responses:
        200:
          description: This is a specific product from the catalog
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 400
                  name:
                    type: string
                    example: Lemon Water

  /product:
    get:
      tags:
        - Product
      parameters:
        - in: query
          name: pageNumber
          description: Page number to return
          required: false
          schema:
            type: integer
            example: 1
        - in: query
          name: pageSize
          description: Number of the items per page
          required: false
          schema:
            type: integer
            example: 10
            maximum: 100
      responses:
        200:
          description: This is a list of the products in the catalog
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      example: 400
                    name:
                      type: string
                      example: Lemon Water
