openapi: 3.0.0
info:
  title: H Plus Sports API
  version: 1.0.0
tags:
  - name: Product
paths:
  /product/{productId}:
    get:
      tags:
        - Product
      parameters:
        - in: path
          name: productId
          description: Product id
          required: true
          schema:
            type: integer
            example: 123
        - in: header
          name: customer-security-header
          description: Customer token
          required: false
          schema:
            type: string
      responses:
        200:
          description: This is a specific product from the catalog
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        500:
          $ref: "#/components/responses/500ApiError"
  /product:
    post:
      tags:
        - Product
      description: Add a product to the catalog
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        201:
          description: The product has been created
        500:
          $ref: "#/components/responses/500ApiError"
    get:
      tags:
        - Product
      parameters:
        - $ref: "#/components/parameters/PageNumber"
        - $ref: "#/components/parameters/PageSize"
      responses:
        200:
          description: This is a list of the products in the catalog
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        500:
          $ref: "#/components/responses/500ApiError"
components:
  parameters:
    PageNumber:
      in: query
      name: pageNumber
      description: Page number to return
      required: false
      schema:
        type: integer
        example: 1
    PageSize:
      in: query
      name: pageSize
      description: Number of the items per page
      required: false
      schema:
        type: integer
        example: 10
        maximum: 100
  schemas:
    Product:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          description: Product id
          example: 123
        name:
          type: string
          description: Product description
          example: Bluetooth mouse
        description:
          type: string
          description: Detailed description of the product
          example: 3-button wireless optical mouse
        image_title:
          type: string
          description: Image title of the product
          example: 3-button-wireless-mouse
        image:
          type: string
          description: Product image's url
          example: https://server.com/images/123.jpeg
  responses:
    500ApiError:
      description: This is an unexpected error
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: string
                example: 500
              message:
                type: string
                example: Server error
