openapi: 3.0.0
info:
  title: H Plus Blog API
  version: 1.0.0
tags:
  - name: Article
    description: Articles for the H Plus Sports Blog
paths:
  /article:
    post:
      tags:
        - Article
      description: Add a new article
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Article"

      responses:
        201:
          description: The article has been created
    get:
      tags:
        - Article
      responses:
        200:
          description: This is a list of the X Blog's articles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Article"
components:
  schemas:
    Article:
      type: object
      required:
        - tagline
        - content
        - category
      properties:
        createdDate:
          format: date
          type: string
        tagline:
          type: string
          example: Tag line example
        content:
          type: string
          example: This could be an html that represents the content of an article
        category:
          type: string
          example: economy
        tags:
          type: array
          items:
            type: string
