openapi: 3.0.0
info:
  title: H Plus Sports Catalog API
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/seibel-personal/h-plus-sports-catalog-api/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: product
  description: This is the product related operations
- name: order
  description: This is the order related operations
paths:
  /order:
    post:
      tags:
      - order
      operationId: orderPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        "201":
          description: The order has been created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        "500":
          description: This is an unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
      security:
      - password:
        - write
      x-swagger-router-controller: Order
  /product/{productId}:
    get:
      tags:
      - product
      operationId: productProductIdGET
      parameters:
      - name: productId
        in: path
        description: Product id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          example: 123
      - name: customer-security-header
        in: header
        description: Customer token
        required: false
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: This is a specific product from the catalog
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "500":
          description: This is an unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
      x-swagger-router-controller: Product
  /product:
    get:
      tags:
      - Product
      operationId: productGET
      parameters:
      - name: pageNumber
        in: query
        description: Page number to return
        required: false
        style: form
        explode: true
        schema:
          type: integer
          example: 1
      - name: pageSize
        in: query
        description: Number of the items per page
        required: false
        style: form
        explode: true
        schema:
          maximum: 100
          type: integer
          example: 10
      responses:
        "200":
          description: This is a list of the products in the catalog
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
                x-content-type: application/json
        "500":
          description: This is an unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
      x-swagger-router-controller: Product
    post:
      tags:
      - Product
      description: Add a product to the catalog
      operationId: productPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        "201":
          description: The product has been created
        "500":
          description: This is an unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
      security:
      - password:
        - write
      x-swagger-router-controller: Product
components:
  schemas:
    Product:
      required:
      - name
      type: object
      properties:
        id:
          type: integer
          description: Product id
          example: 123
        name:
          type: string
          description: Product description
          example: Bluetooth mouse
        description:
          type: string
          description: Detailed description of the product
          example: 3-button wireless optical mouse
        image_title:
          type: string
          description: Image title of the product
          example: 3-button-wireless-mouse
        image:
          type: string
          description: Product image's url
          example: https://server.com/images/123.jpeg
      example:
        image: https://server.com/images/123.jpeg
        name: Bluetooth mouse
        description: 3-button wireless optical mouse
        id: 123
        image_title: 3-button-wireless-mouse
    Order:
      type: object
      properties:
        id:
          type: integer
          example: 1
        productId:
          type: integer
          example: 1234
        quantity:
          type: integer
          example: 1
        orderDate:
          type: string
          format: date-time
          example: 2022-01-31T12:13:00-08:00
        customer:
          $ref: '#/components/schemas/Customer'
      example:
        quantity: 1
        productId: 1234
        id: 1
        orderDate: 2022-01-31T12:13:00-08:00
        customer:
          firstName: John
          lastName: Doe
          phoneNumber: 55-5555-5555
          customerNumber: 1g23g41i34
    Customer:
      required:
      - customerNumber
      - firstName
      - lastName
      type: object
      properties:
        customerNumber:
          type: string
          example: 1g23g41i34
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        phoneNumber:
          type: string
          example: 55-5555-5555
      example:
        firstName: John
        lastName: Doe
        phoneNumber: 55-5555-5555
        customerNumber: 1g23g41i34
    inline_response_500:
      type: object
      properties:
        statusCode:
          type: string
          example: "500"
        message:
          type: string
          example: Server error
  responses:
    "500ApiError":
      description: This is an unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response_500'
  parameters:
    PageNumber:
      name: pageNumber
      in: query
      description: Page number to return
      required: false
      style: form
      explode: true
      schema:
        type: integer
        example: 1
    PageSize:
      name: pageSize
      in: query
      description: Number of the items per page
      required: false
      style: form
      explode: true
      schema:
        maximum: 100
        type: integer
        example: 10
  securitySchemes:
    password:
      type: oauth2
      flows:
        password:
          tokenUrl: http://example.com/oauth/token
          scopes:
            write: allows modifying resources
            read: allows reading resources
